version: '3.8'

services:
  mongodb:
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  blog:
    depends_on:
      - mongodb
    build: .
    image: blog:latest
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
      MONGO_DATABASE: admin